export const FIELDS_GYM = [
	"id",
	"lat",
	"lon",
	"name",
	"url",
	"description",
	"last_modified_timestamp",
	"updated",
	"first_seen_timestamp",
	"raid_end_timestamp",
	"raid_spawn_timestamp",
	"raid_battle_timestamp",
	"raid_pokemon_id",
	"raid_pokemon_form",
	"raid_pokemon_cp",
	"raid_pokemon_move_1",
	"raid_pokemon_move_2",
	"raid_pokemon_gender",
	"raid_pokemon_costume",
	"raid_pokemon_evolution",
	"raid_pokemon_alignment",
	"raid_level",
	"team_id",
	"availble_slots",
	"in_battle",
	"ex_raid_eligible",
	"ar_scan_eligible",
	"power_up_level",
	"power_up_points",
	"power_up_end_timestamp",
	"defenders",
	"rsvps",
	"deleted"
].join(",");

export const FIELDS_STATION = [
	"id",
	"lat",
	"lon",
	"name",
	"start_time",
	"end_time",
	"is_battle_available",
	"is_inactive",
	"battle_level",
	"battle_pokemon_id",
	"battle_pokemon_form",
	"battle_pokemon_costume",
	"battle_pokemon_gender",
	"battle_pokemon_alignment",
	"battle_pokemon_bread_mode",
	"battle_pokemon_move_1",
	"battle_pokemon_move_2",
	"updated",
	"total_stationed_pokemon",
	"total_stationed_gmax",
	"stationed_pokemon"
].join(",");

export const FIELDS_SPAWNPOINT = [
	"CONVERT(id, CHAR) AS id",
	"lat",
	"lon",
	"updated",
	"last_seen",
	"despawn_sec",
	"first_seen"
].join(",");

export const FIELDS_NEST = [
	"nest_id as id",
	"lat",
	"lon",
	"name",
	"polygon",
	"spawnpoints",
	"m2",
	"active",
	"pokemon_id",
	"pokemon_form AS form",
	"pokemon_avg",
	"pokemon_ratio",
	"pokemon_count",
	"discarded",
	"updated"
].join(",");

export const FIELDS_TAPPABLE = [
	"id",
	"lat",
	"lon",
	"lat",
	"lon",
	"type as tappable_type",
	"pokemon_id",
	"item_id",
	"count",
	"expire_timestamp_verified",
	"expire_timestamp",
	"updated"
].join(",");

export const FIELDS_ROUTE = [
	"id",
	"start_lat as lat",
	"start_lon as lon",
	"name",
	"shortcode",
	"description",
	"distance_meters",
	"duration_seconds",
	"start_fort_id",
	"start_image",
	"start_lat",
	"start_lon",
	"end_fort_id",
	"end_image",
	"end_lat",
	"end_lon",
	"image",
	"image_border_color",
	"reversible",
	"tags",
	"type as route_type",
	"updated",
	"version",
	"waypoints"
].join(",");

export const FIELDS_POKESTOP = [
	"pokestop.id",
	"pokestop.lat",
	"pokestop.lon",
	"pokestop.name",
	"pokestop.url",
	"pokestop.description",
	"pokestop.lure_expire_timestamp",
	"pokestop.last_modified_timestamp",
	"pokestop.updated",
	"pokestop.first_seen_timestamp",
	"pokestop.deleted",
	"pokestop.lure_id",
	"pokestop.ar_scan_eligible",
	"pokestop.power_up_level",
	"pokestop.power_up_points",
	"pokestop.power_up_end_timestamp",
	"pokestop.quest_timestamp",
	"pokestop.quest_target",
	"pokestop.quest_rewards",
	"pokestop.quest_title",
	"pokestop.quest_expiry",
	"pokestop.alternative_quest_timestamp",
	"pokestop.alternative_quest_target",
	"pokestop.alternative_quest_rewards",
	"pokestop.alternative_quest_title",
	"pokestop.alternative_quest_expiry",
	"pokestop.showcase_pokemon_id",
	"pokestop.showcase_pokemon_form_id",
	"pokestop.showcase_focus",
	"pokestop.showcase_pokemon_type_id",
	"pokestop.showcase_ranking_standard",
	"pokestop.showcase_expiry",
	"pokestop.showcase_rankings"
].join(",");

export const FIELDS_INCIDENT = [
	"incident.id",
	"incident.pokestop_id",
	"incident.expiration",
	"incident.display_type",
	"incident.character",
	"incident.confirmed",
	"incident.slot_1_pokemon_id",
	"incident.slot_1_form",
	"incident.slot_2_pokemon_id",
	"incident.slot_2_form",
	"incident.slot_3_pokemon_id",
	"incident.slot_3_form"
].join(",");